-- db/supabase/migrations/0010_storage.sql
-- Storage buckets and Row Level Security policies for eRTMAC-NWIS (SIH26121)
-- Contract §8

/*
  Storage Architecture & Upload Flow:
  -----------------------------------
  1. Browser Uploads:
     - Direct browser uploads to Supabase Storage bypass serverless body limits.
     - The browser calls the Node API route `/api/documents/upload-url` with JWT authentication.
     - The Node route verifies permissions (reviewer, office_engineer, admin) and generates a
       signed upload URL using the Supabase Service Role key:
         createSignedUploadUrl('incoming/{upload_id}/{filename}')
     - The browser uploads directly to this signed upload URL.
     - This flow requires NO direct INSERT policy for users on `storage.objects`.
     - The backend ingestion service later processes and moves the file to `{doc_id}/{filename}`.

  2. Frontend Reads:
     - All buckets are private (public = false).
     - Authenticated users read document files and page images via time-limited signed URLs
       generated by the frontend / API using `createSignedUrl` (e.g. 1 hour expiry).
     - RLS policy on `storage.objects` permits SELECT for role `authenticated` on `documents`
       and `page-images`.

  3. Model Artifacts:
     - The `models` bucket stores model weights/artifacts ({version}.joblib).
     - It is strictly accessible by the backend using the service role only (no user access).
*/

-- 1. Insert buckets into storage.buckets (id, name, public=false, file_size_limit, allowed_mime_types)
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values
  (
    'documents',
    'documents',
    false,
    26214400, -- 25 MB (25 * 1024 * 1024 bytes)
    array[
      'application/pdf',
      'image/png',
      'image/jpeg',
      'image/tiff',
      'text/csv',
      'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
      'application/xml',
      'text/xml',
      'text/plain',
      'application/octet-stream' -- LAS files
    ]::text[]
  ),
  (
    'page-images',
    'page-images',
    false,
    10485760, -- 10 MB limit for page render images
    array['image/png', 'image/jpeg', 'image/webp']::text[]
  ),
  (
    'models',
    'models',
    false,
    null,     -- Managed by backend
    null      -- Internal binary model artifacts (.joblib)
  )
on conflict (id) do update set
  public = excluded.public,
  file_size_limit = coalesce(excluded.file_size_limit, storage.buckets.file_size_limit),
  allowed_mime_types = coalesce(excluded.allowed_mime_types, storage.buckets.allowed_mime_types);

-- 2. Storage Objects Policies
-- Authenticated users can SELECT (read) from 'documents' and 'page-images'
drop policy if exists "storage_objects_select_authenticated" on storage.objects;
create policy "storage_objects_select_authenticated"
on storage.objects
for select
to authenticated
using (bucket_id in ('documents', 'page-images'));

-- No user insert/update/delete policies are created.
-- Browser uploads use signed upload URLs generated by the service role.
-- Backend processes and moves files using the service role.
-- Models bucket has no user access policies (accessible solely via service role).
