-- db/supabase/seed.sql
-- Reference data seed for eRTMAC-NWIS (SIH26121)
-- Contains reference formations, synonyms, and IADC DDR Plus codes.

-- 1. Formations (Upper Assam and Volve basins)
insert into formations (name, basin, strat_order, lithology, typical_risks) values
  ('Alluvium', 'Upper Assam', 1, 'Unconsolidated sand, clay', array['losses'::risk_type]),
  ('Dhekiajuli', 'Upper Assam', 2, 'Sand, clay', array['losses'::risk_type]),
  ('Namsang', 'Upper Assam', 3, 'Sandstone, conglomerate', array['losses'::risk_type]),
  ('Girujan', 'Upper Assam', 4, 'Mottled clay', array['stuck_pipe'::risk_type]),
  ('Tipam', 'Upper Assam', 5, 'Sandstone, minor shale', array['losses'::risk_type, 'cementing'::risk_type]),
  ('Barail', 'Upper Assam', 6, 'Shale, sandstone, coal', array['stuck_pipe'::risk_type, 'torque'::risk_type]),
  ('Kopili', 'Upper Assam', 7, 'Shale', array['kick'::risk_type, 'stuck_pipe'::risk_type]),
  ('Sylhet', 'Upper Assam', 8, 'Limestone, shale', array['losses'::risk_type, 'kick'::risk_type]),
  ('Langpar', 'Upper Assam', 9, 'Sandstone, shale', array['kick'::risk_type]),
  ('Basement', 'Upper Assam', 10, 'Granite, gneiss', array[]::risk_type[]),
  ('Nordland Gp', 'Volve', 1, 'Clay, sand', array[]::risk_type[]),
  ('Hordaland Gp', 'Volve', 2, 'Claystone', array['stuck_pipe'::risk_type]),
  ('Rogaland Gp', 'Volve', 3, 'Claystone, tuff', array[]::risk_type[]),
  ('Shetland Gp', 'Volve', 4, 'Chalk, limestone', array['losses'::risk_type]),
  ('Cromer Knoll Gp', 'Volve', 5, 'Marl', array[]::risk_type[]),
  ('Viking Gp', 'Volve', 6, 'Shale (Draupne, Heather)', array['stuck_pipe'::risk_type, 'kick'::risk_type]),
  ('Hugin Fm', 'Volve', 7, 'Sandstone (reservoir)', array['losses'::risk_type]),
  ('Skagerrak Fm', 'Volve', 8, 'Sandstone, conglomerate', array['losses'::risk_type]),
  ('Smith Bank Fm', 'Volve', 9, 'Claystone', array[]::risk_type[])
on conflict (name) do nothing;

-- 2. Formation Synonyms (canonical lowercased + field and literature aliases)
insert into formation_synonyms (alias, formation) values
  ('alluvium', 'Alluvium'),
  ('dhekiajuli', 'Dhekiajuli'),
  ('namsang', 'Namsang'),
  ('girujan', 'Girujan'),
  ('tipam', 'Tipam'),
  ('barail', 'Barail'),
  ('kopili', 'Kopili'),
  ('sylhet', 'Sylhet'),
  ('langpar', 'Langpar'),
  ('basement', 'Basement'),
  ('nordland gp', 'Nordland Gp'),
  ('hordaland gp', 'Hordaland Gp'),
  ('rogaland gp', 'Rogaland Gp'),
  ('shetland gp', 'Shetland Gp'),
  ('cromer knoll gp', 'Cromer Knoll Gp'),
  ('viking gp', 'Viking Gp'),
  ('hugin fm', 'Hugin Fm'),
  ('skagerrak fm', 'Skagerrak Fm'),
  ('smith bank fm', 'Smith Bank Fm'),
  ('tipam sandstone', 'Tipam'),
  ('tipam ss', 'Tipam'),
  ('tipam fm', 'Tipam'),
  ('barail group', 'Barail'),
  ('barail coal shale', 'Barail'),
  ('barail fm', 'Barail'),
  ('girujan clay', 'Girujan'),
  ('girujan clays', 'Girujan'),
  ('kopili shale', 'Kopili'),
  ('sylhet limestone', 'Sylhet'),
  ('sylhet lst', 'Sylhet'),
  ('hugin', 'Hugin Fm'),
  ('hugin formation', 'Hugin Fm'),
  ('draupne', 'Viking Gp'),
  ('heather', 'Viking Gp'),
  ('viking', 'Viking Gp'),
  ('skagerrak', 'Skagerrak Fm')
on conflict (alias) do nothing;

-- 3. IADC DDR Plus Codes (34 standard activity codes)
insert into iadc_codes (code, name, is_trouble) values
  (1, 'Rig up / tear down / rig move', false),
  (2, 'Drilling', false),
  (3, 'Reaming', true),
  (4, 'Coring', false),
  (5, 'Circulate & condition mud', true),
  (6, 'Trips', false),
  (7, 'Service / maintain rig', false),
  (8, 'Repair rig', false),
  (9, 'Replacing drill line', false),
  (10, 'Deviation survey', false),
  (11, 'Wireline logs', false),
  (12, 'Run casing & cement', false),
  (13, 'Wait on cement', false),
  (14, 'Rig up/down BOP', false),
  (15, 'Test BOP', false),
  (16, 'Drill stem test', false),
  (17, 'Plug back', false),
  (18, 'Squeeze cement', false),
  (19, 'Fishing', true),
  (20, 'Specialized directional work', false),
  (21, 'Run/retrieve riser equipment', false),
  (22, 'Surface testing', false),
  (23, 'Other', false),
  (24, 'Non-productive time', true),
  (25, 'Operating status', false),
  (26, 'Safety', false),
  (27, 'Well control', true),
  (28, 'Coiled tubing', false),
  (29, 'Perforating', false),
  (30, 'Tubing trips', false),
  (31, 'Treating & well completion', false),
  (32, 'Swabbing', false),
  (33, 'Testing', false),
  (34, 'Subsea installations', false)
on conflict (code) do nothing;
